### ISSUE TITLE
Get a replacement Kerberos container

### ISSUE THREAD

**Issue by afolarin** [RADAR-CNS/RADAR-Docker#4]
Although listed in the examples folder SASL Confluent Platform dockerized stack, the Kerberos container used doesn't exist or is private (more likely part of some enterprise stack Confluent are holding back)

i.e. https://github.com/confluentinc/cp-docker-images/tree/master/examples/kafka-cluster-sasl
```yml
 kerberos:
    image: confluentinc/cp-kerberos:latest
    network_mode: host
    environment:
      BOOTSTRAP: 0
    volumes:
    - ${KAFKA_SASL_SECRETS_DIR}:/tmp/keytab
    - /dev/urandom:/dev/random
```

If we want to use this for AuthN we should try create a new one.
